export type WTCatalog = "base_name" |
"payment_type" |
"good_type" |
"payment" |
"benefit_item" |
"good_instance" |
"basket" |
"org" |
"subdivision_group" |
"collaborator" |
"subdivision" |
"availability_plan" |
"position" |
"group" |
"position_common_instruction" |
"qualification_assignment" |
"substitution" |
"staff_position_start" |
"position_common" |
"qualification" |
"position_family" |
"substitution_type" |
"staff_position" |
"staff_position_finish" |
"benefit" |
"staff_position_move" |
"salary_survey_source" |
"position_level" |
"salary_survey" |
"good" |
"order" |
"outstaff_contract" |
"expert_question" |
"outstaff_order_execution" |
"outstaff_additional_work" |
"knowledge_part" |
"knowledge_part_level" |
"knowledge_acquaint" |
"article" |
"tag" |
"career_plan" |
"expert" |
"outstaff_provider" |
"outstaff_order" |
"outstaff_type_material" |
"knowledge_classifier" |
"book" |
"knowledge_part_type" |
"knowledge_profile" |
"acquaint" |
"career_reserve" |
"resume" |
"personnel_committee" |
"successor" |
"exclusion_reason" |
"typical_development_program" |
"skill" |
"development_potential" |
"risk_perspective" |
"section_instruction" |
"key_position" |
"course" |
"personnel_reserve" |
"committee_member" |
"talent_pool_nomination" |
"readiness_level" |
"career_reserve_type" |
"professional_area" |
"efficiency_estimation" |
"risk_level" |
"key_position_threat" |
"tutor" |
"course_module" |
"active_learning" |
"learning_part" |
"assessment" |
"document_comment_entry" |
"role" |
"test_learning" |
"proctoring_system" |
"recruitment_system" |
"poll_result" |
"forum" |
"forum_theme_read_by_collaborator" |
"learning" |
"item" |
"test_project" |
"active_test_learning" |
"poll" |
"learning_record" |
"testing_system" |
"document" |
"poll_procedure" |
"forum_entry" |
"blog" |
"blog_entry" |
"chat" |
"conversation_type" |
"call" |
"active_web_template" |
"banner" |
"host" |
"web_design" |
"change" |
"invoice" |
"expense_item" |
"blog_entry_comment" |
"conversation" |
"block_message" |
"web_person_state" |
"like" |
"subscription" |
"site" |
"web_mode" |
"transaction" |
"account" |
"cost_center" |
"budget_period" |
"budget" |
"contract" |
"education_org" |
"lector" |
"education_method" |
"education_program" |
"event_type" |
"education_plan" |
"traning_order" |
"learning_task_result" |
"pay_phase" |
"budget_type" |
"level" |
"provider_course_type" |
"object_resource" |
"compound_program" |
"event" |
"event_result" |
"training_plan" |
"learning_task" |
"contest" |
"participant" |
"resource" |
"script_queue_elem" |
"response" |
"workflow" |
"webinar_system" |
"server_agent" |
"notification" |
"file_source" |
"request_type" |
"event_result_type" |
"place" |
"resource_type" |
"request" |
"discharge" |
"exchange_server" |
"library_system" |
"code_library" |
"notification_template" |
"custom_report" |
"response_type" |
"notification_system" |
"coding" |
"object_data" |
"doc_type" |
"custom_web_template_group" |
"application" |
"project" |
"project_participant_role" |
"contact_type" |
"kpi" |
"kpi_profile" |
"formula" |
"object_data_type" |
"ui_data" |
"custom_web_template" |
"digital_signature" |
"application_instance" |
"project_participant" |
"contact" |
"contact_result" |
"kpi_group" |
"scale" |
"kpi_plan" |
"kpi_value" |
"indicator" |
"assessment_appraise" |
"supplementary_question" |
"print_form" |
"competence_block" |
"bonus_profile" |
"development_method" |
"user_assignment" |
"competence_profile_family" |
"exercise" |
"competence" |
"competence_profile" |
"pa" |
"assessment_result_recommend" |
"covenant" |
"development_plan" |
"bonus_item" |
"assessment_plan" |
"assessment_appraise_matrix" |
"rating" |
"operation" |
"boss_type" |
"objective_translate" |
"task" |
"project_type" |
"statistic_rec" |
"active_notification" |
"order_type" |
"system_event" |
"event_assessment_plan" |
"certificate_type" |
"vacancy_subscription" |
"grade" |
"position_assessment_form" |
"task_type" |
"action_report" |
"statistic_data" |
"connection" |
"contract_type" |
"system_event_handler" |
"certificate" |
"region" |
"selected_vacancy" |
"vacancy_response" |
"candidate_status_type" |
"vacancy_source" |
"vacancy_type" |
"recruitment_event" |
"personal_data_processing_consent" |
"candidate_source" |
"estaff_event_type" |
"submission_type" |
"person_object_link" |
"custom_admin_template" |
"vacancy" |
"work_schedule" |
"selected_resume" |
"recruitment_plan" |
"submission" |
"recruitment_method" |
"recommendation" |
"estaff_event" |
"override_web_template" |
"person_object_profile" |
"cl_course" |
"cl_module" |
"cl_object" |
"cl_localization" |
"library_material" |
"library_material_source_type" |
"library_section" |
"library_material_format" |
"library_material_viewing" |
"repositorium" |
"org_vendor_state" |
"remote_collection" |
"cl_slide" |
"cl_shape" |
"cl_const" |
"library_material_item" |
"library_player" |
"library_material_type" |
"library_material_comment" |
"license" |
"vendor_state" |
"remote_action" |
"remote_security_profile" |
"remote_application" |
"download_package" |
"object_version" |
"profiling_record" |
"dn_special" |
"dn_discipline" |
"dn_academ_year" |
"dn_educat_event" |
"dn_program_discipl" |
"dn_edu_condition" |
"dn_term" |
"credential" |
"upload_package" |
"user_data" |
"dn_auditorium" |
"dn_specialization" |
"dn_block_discipline" |
"dn_control_form" |
"dn_educat_form" |
"dn_prog_disc_append" |
"dn_train_method_complex" |
"dn_student" |
"dn_stud_centrtest_result" |
"dn_stream" |
"dn_ind_educat_plan" |
"dn_lesson" |
"walkthrough" |
"dn_control_event" |
"dn_academ_debt" |
"web_rule" |
"activity" |
"learning_storage" |
"verb" |
"dn_stud_group" |
"dn_subject_plan" |
"dn_work_curriculum" |
"dn_schedule" |
"statement" |
"dn_register" |
"plugin" |
"external_system" |
"activity_state" |
"profile" |
"reprimand" |
"reprimand_type" |
"chatbot" |
"chatbot_stage" |
"custom_chatbot_template" |
"dimension" |
"mobile_app_config" |
"sale" |
"price" |
"pay_stage" |
"closing_document" |
"acquaint_assign" |
"chatbot_chat" |
"chatbot_type" |
"component_package" |
"sale_contract" |
"device_reg" |
"provider" |
"expense" |
"fact_payment" |
"closing_document_status" |
"sale_status" |
"contract_state" |
"messenger_service" |
"wiki_article_type" |
"wiki_article_communication_type" |
"policy_type" |
"collaborator_schedule" |
"presence_state" |
"check_schedule" |
"presentation" |
"education_form" |
"work_condition" |
"policy" |
"sale_contract_type" |
"wiki_base" |
"wiki_article" |
"wiki_article_communication" |
"education_type" |
"schedule_day" |
"schedule_type" |
"vclass_setting" |
"skill_type" |
"vacancy_reason" |
"wage_system" |
"object_link" |
"work_experience" |
"profession" |
"appointment_type" |
"time_entry" |
"absence_reserve" |
"recommender_algorithm" |
"recommender_select_collaborator" |
"view_configuration" |
"work_mode" |
"material_liability" |
"education_mode" |
"profession_category" |
"user_recommendation" |
"professional_area_type" |
"restricting_type" |
"restricting_collaborator_schedule" |
"recommender_algorithm_applying" |
"admin_configuration" |
"qa_test" |
"qa_test_set" |
"qa_test_result" |
"interval_schedule" |
"statement_attachment" |
"work_schedule_type" |
"work_form" |
"statement_actor" |
"statement_component" |
"personnel_document_type" |
"cl_video_course" |
"qa_test_paramset" |
"channel_provider" |
"salary_payment_type" |
"working_condition_type" |
"statement_additional" |
"working_condition" |
"statement_object" |
"statement_pattern" |
"personnel_document" |
"object_claim"
