stages:
  - build

build-job:
  stage: build
  image: node:20.19.1-bookworm-slim
  tags:
    - docker
  script:
    - npm ci
    - npm run build
    - npm run docs          
  artifacts:
    paths:
      - dist/
      - docs/
    expire_in: 1 week
    